employee/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views
from .views import UserRegisterView

app_name = "employee"

urlpatterns = [
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("list/", views.IndexView.as_view(), name="index"),
    path("add/employee/", views.EmployeeAddView.as_view(), name="add_employee"),
    path(
        "update/employee/<str:eid>/",
        views.EmployeeUpdateView.as_view(),
        name="update_employee",
    ),
    path("employee/<str:eid>/", views.EmployeeDetailView.as_view(), name="detail"),
    path(
        "employee/<str:eid>/add/skill/",
        views.SkillAddView.as_view(),
        name="add_skill",
    ),
    path(
        "employee/skill/update/<int:pk>/",
        views.SkillUpdateView.as_view(),
        name="update_skill",
    ),
    path("delete/<str:eid>/", views.EmployeeDeleteView.as_view(), name="delete"),
]

empsys/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

employee/models.py
from django.db import models
from django.utils import timezone


def get_or_create_eid():
    employee, _ = Employee.objects.get_or_create(eid="XXXX.YYYY")
    return employee


class Employee(models.Model):
    eid = models.CharField("EID", max_length=50, primary_key=True)
    eno = models.CharField(
        "Employee No.", max_length=8, unique=True, default="00000000"
    )
    first_name = models.CharField(
        "First Name",
        max_length=20,
        default="XXXX",
    )
    middle_name = models.CharField("Middle Name", max_length=20, blank=True)
    last_name = models.CharField("Last Name", max_length=20, default="YYYY")
    full_name = models.CharField("Name", max_length=50)
    email = models.EmailField("e-mail", blank=True)
    dte = models.CharField("DTE", max_length=10, default="XXXX")
    office = models.CharField("Office", max_length=20, default="AIR")
    created_at = models.DateTimeField("Resister Date", auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.eid:
            base_eid = f"{self.first_name.lower()}.{self.last_name.lower()}"
            eid = base_eid
            counter = 0

            while Employee.objects.filter(eid=eid).exists():
                counter += 1
                eid = f"{base_eid}.{chr(64 + counter)}"  # A, B, C, ...

            self.eid = eid
            self.email = f"{self.eid}@accenture.com"
            self.full_name = f"{self.first_name} {self.middle_name} {self.last_name}"

        super(Employee, self).save(*args, **kwargs)

    def __str__(self):
        return self.eid


class Project(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField("Project Name", max_length=50, default="XXXX")
    start_date = models.DateTimeField("Start Date", default=timezone.now)
    end_date = models.DateTimeField("End Date", blank=True, null=True)
    description = models.TextField("Project Detail", blank=True, null=True)
    created_at = models.DateTimeField()

    def __str__(self):
        return self.name


class Skill(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField("Skill Name", max_length=100, default="XXXX")
    employee = models.ForeignKey(
        Employee,
        on_delete=models.PROTECT,
        to_field="eid",
        related_name="skills",
        default=get_or_create_eid,
    )
    level = models.CharField(max_length=2, blank=True, null=True)
    acquire_date = models.DateField(blank=True, null=True)
    expire_date = models.DateField(blank=True, null=True)
    need_update = models.BooleanField(default=False)


class Training(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=100, default="XXXX")
    employee = models.ForeignKey(
        Employee,
        on_delete=models.PROTECT,
        to_field="eid",
        related_name="trainings",
        default=get_or_create_eid,
    )
    completion_date = models.DateField(blank=True, null=True)

employee/forms.py
from django import forms

from .models import Employee, Skill, Training


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"


class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = "__all__"
        widgets = {"employee": forms.HiddenInput()}


class TrainingForm(forms.ModelForm):
    class Meta:
        model = Training
        fields = "__all__"

employee/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView

from .forms import EmployeeForm, SkillForm
from .models import Employee, Skill, Training
from .views_common import BaseView, EIDMixin, SuccessUrlMixin


class UserRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("employee:login")  # 登録後にログインページにリダイレクト

    def form_valid(self, form):
        valid = super().form_valid(form)
        # ここで追加の処理を行うことができます（例えばユーザーにメールを送信する等）
        return valid


class IndexView(BaseView, generic.ListView):
    model = Employee
    paginate_by = 5
    template_name = "employee_list.html"


class EmployeeDetailView(BaseView, EIDMixin, generic.DetailView):
    model = Employee
    template_name = "employee/employee_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        employee = self.get_object()
        context["skills"] = Skill.objects.filter(employee=employee)
        context["trainings"] = Training.objects.filter(employee=employee)
        return context


class EmployeeAddView(BaseView, generic.CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = "employee/employee_form.html"
    success_url = reverse_lazy("employee:index")


class EmployeeUpdateView(BaseView, EIDMixin, generic.UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name = "employee/employee_form.html"

    def get_success_url(self):
        """更新が成功した後のリダイレクト先URLを指定"""
        return reverse_lazy("employee:detail", kwargs={"eid": self.get_object().eid})


class EmployeeDeleteView(BaseView, generic.DeleteView):
    model = Employee
    success_url = reverse_lazy("employee:index")


class SkillAddView(BaseView, generic.CreateView):
    model = Skill
    form_class = SkillForm
    template_name = "employee/skill_form.html"

    def get_initial(self):
        initial = super().get_initial()
        # URLからeidを取得し、対応するEmployeeオブジェクトを検索
        eid = self.kwargs.get("eid")
        # EmployeeオブジェクトのIDをemployeeフィールドの初期値として設定
        initial["employee"] = eid
        return initial

    def get_success_url(self):
        eid = self.kwargs.get("eid")
        return reverse_lazy("employee:detail", kwargs={"eid": eid})


class SkillUpdateView(BaseView, SuccessUrlMixin, UpdateView):
    model = Skill
    form_class = SkillForm
    template_name = "employee/skill_form.html"


class SkillDeleteView(BaseView, SuccessUrlMixin, generic.DeleteView):
    model = Skill
    form_class = SkillForm

employee/templates/employee/employee_detail.html
{% extends 'format/base.html' %}

{% block content %}
<h1>{{ employee.eid }}</h1>
<!-- employee.eid を直接表示 -->
<h3>
    個人基本情報
    <a href="{% url 'employee:update_employee' employee.eid %}" style="font-size: 18px;">更新</a>
</h3>
<ul>
    <!-- DetailView では単一のオブジェクトを扱うので、ループ不要 -->
    <li>名前: {{ employee.first_name }} {{ employee.middle_name }} {{ employee.last_name }}</li>
    <li>フルネーム: {{ employee.full_name }}</li>
    <li>Eメール: {{ employee.email }}</li>
    <li>DTE: {{ employee.dte }}</li>
    <li>所属オフィス: {{ employee.office }}</li>
    <li>登録日: {{ employee.created_at }}</li>
</ul>
<h3>
    スキル情報
    <a href="{% url 'employee:add_skill' eid=employee.eid %}" style="font-size: 18px;">追加</a>
</h3>
<ul>
    {% for skill in skills %}
    <li>
        {{ skill.name }}: Level {{ skill.level }}
        <a href="{% url 'employee:update_skill' skill.id %}">更新</a>
    </li>
    保有期間: {{ skill.acquire_date }} - {{skill.expire_date}}
    {% endfor %}
</ul>
<h3>
    トレーニング情報
</h3>
<ul>
    {% for training in trainings %}
    <li>
        {{ training.name }} - 完了日: {{ training.completion_date }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

employee/templates/employee/employee_form.html
{% extends 'format/base.html' %}

{% block content %}
<h4>社員追加</h4>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

employee/templates/employee/employee_list.html
{% extends 'format/base.html' %}

{% block content %}
<h4>社員一覧</h4>
<table class="table table-bordered mt-4">
    <thead>
        <tr>
            <th>EID</th>
            <th>姓</th>
            <th>名</th>
            <th>Eメール</th>
            <th>DTE</th>
        </tr>
    </thead>
    <tbody>
        {% for employee in employee_list %}
        <tr>
            <td>
                <a href="{% url 'employee:detail' employee.eid %}">{{ employee.eid }}</a>
            </td>
            <td>{{ employee.last_name }}</td>
            <td>{{ employee.first_name }}</td>
            <td>{{ employee.email }}</td>
            <td>{{ employee.dte }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include 'format/page5.html' %}
{% endblock %}

employee/templates/employee/skill_form.html
{% extends 'format/base.html' %}

{% block content %}
<h4>スキル追加</h4>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

employee/templates/format/base.html
<!doctype html>
<html lang="ja">
    <head>
        <title>社員管理システム</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link
            rel="stylesheet"
            href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
            integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
            crossorigin="anonymous"
        >
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">社員管理システム</a>
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employee:index' %}">社員一覧</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employee:add_employee' %}">社員追加</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">管理者権限</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employee:login' %}">ログアウト</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block content %}
      {% endblock %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </body>
</html>

employee/templates/format/page4.html
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

employee/templates/format/page5.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>